driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  #- name: centos-6.8
  - name: centos-7.3
  #- name: ubuntu-14.04
  #- name: ubuntu-16.04

suites:
- name: default
  run_list:
  - recipe[test::add-ons-no-fqdn]
  #driver:
   # network:
    #  - ['private_network', {ip: '192.168.50.20'}]
